version: "3.8"
services:
  # app:
  #   build: .
  #   image: market-api
  #   environment: 
  #     DB_ADDRESS: db
  #     POSTGRESQL_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
  #   volumes: 
  #     - ./migrations:/migrations
  #   depends_on: 
  #     - db

  db:
    image: postgres:13.3
    restart: always
    environment: 
        POSTGRES_PASSWORD: $DB_PASSWORD
        POSTGRES_USER: $DB_USER
        POSTGRES_DB: $DB_NAME
    ports:
      - "$DB_PORT:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
  
  db_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
volumes:
  data:
